kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: csi-cetusfs-snapshotter
spec:
  serviceName: "csi-cetusfs-snapshotter"
  replicas: 1
  selector:
    matchLabels:
      app: csi-cetusfs-snapshotter
  template:
    metadata:
      labels:
        app: csi-cetusfs-snapshotter
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - csi-cetusfsplugin
            topologyKey: kubernetes.io/hostname
      serviceAccount: csi-snapshotter
      containers:
        - name: csi-snapshotter
          image: k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.0
          args:
            - -v=5
            - --csi-address=/csi/csi.sock
          securityContext:
            # This is necessary only for systems with SELinux, where
            # non-privileged sidecar containers cannot access unix domain socket
            # created by privileged CSI driver container.
            privileged: true
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
      volumes:
        - hostPath:
            path: /var/lib/kubelet/plugins/csi-cetusfs
            type: DirectoryOrCreate
          name: socket-dir
