apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-csi-cetusfs-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-cetusfs-sc # defined in csi-storageclass.yaml
